export const THEME_CONFIG = {
  font: {
    boldFontFamily: 'Inter-Bold',
    lightFontFamily: 'Inter-Light',
    mediumFontFamily: 'Inter-Medium',
    regularFontFamily: 'Inter-Regular',
    thinFontFamily: 'Inter-Thin',
  },
  colors: {
    light: {
      primaryColor: '#2C2738',
      secondaryColor: '#756F86',
      accentColor: '#2B78E4',
      buttonTextColor: '#ffffff',
      containerColor: '#ffffff',
      textColor: '#2C2738',
      iconColor: '#000000',
      dividerColor: '#d8d8d8',
      errorColor: '#4F4DFE',
      warningColor: '#FE6F00',
      successColor: '#1BC4B9',
      infoColor: '#FDFF18',
      linkTextColor: '#2B78E4',
    },
    dark: {
      primaryColor: '#ffffff',
      secondaryColor: '#756F86',
      accentColor: '#2B78E4',
      buttonTextColor: '#ffffff',
      containerColor: '#3C3747',
      textColor: '#ffffff',
      iconColor: '#ffffff',
      dividerColor: '#ffffff',
      errorColor: '#4F4DFE',
      warningColor: '#FE6F00',
      successColor: '#1BC4B9',
      infoColor: '#FDFF18',
      linkTextColor: '#FCFDFE',
    },
    drawerLight: {
      containerColor: '#ffffff',
      textColor: '#2C2738',
      iconColor: '#2C2738',
      dividerColor: '#2C2738',
    },
    drawerDark: {
      containerColor: '#011429',
      textColor: '#A5A9AD',
      iconColor: '#A5A9AD',
      dividerColor: '#A5A9AD',
    },
  },
  buttons: {
    borderRadius: 5,
    height: 40,
  },
  sidebar: 'dark',
};
